2020-02-20T00:36:59.506-0600 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-02-20T00:36:59.551-0600 I  CONTROL  [initandlisten] MongoDB starting : pid=28346 port=27017 dbpath=./db 64-bit host=Sarans-MBP-189
2020-02-20T00:36:59.551-0600 I  CONTROL  [initandlisten] db version v4.2.3
2020-02-20T00:36:59.551-0600 I  CONTROL  [initandlisten] git version: 6874650b362138df74be53d366bbefc321ea32d4
2020-02-20T00:36:59.551-0600 I  CONTROL  [initandlisten] allocator: system
2020-02-20T00:36:59.551-0600 I  CONTROL  [initandlisten] modules: none
2020-02-20T00:36:59.551-0600 I  CONTROL  [initandlisten] build environment:
2020-02-20T00:36:59.551-0600 I  CONTROL  [initandlisten]     distarch: x86_64
2020-02-20T00:36:59.551-0600 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-02-20T00:36:59.551-0600 I  CONTROL  [initandlisten] options: { config: "mongoServer.config", net: { bindIp: "127.0.0.1", port: 27017 }, storage: { dbPath: "./db" }, systemLog: { destination: "file", logAppend: true, path: "./mongo.server.log" } }
2020-02-20T00:36:59.553-0600 E  STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
2020-02-20T00:36:59.556-0600 I  CONTROL  [initandlisten] now exiting
2020-02-20T00:36:59.556-0600 I  CONTROL  [initandlisten] shutting down with code:48
2020-02-20T00:38:03.663-0600 I  CONTROL  [main] ***** SERVER RESTARTED *****
2020-02-20T00:38:03.666-0600 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-02-20T00:38:03.671-0600 I  CONTROL  [initandlisten] MongoDB starting : pid=28891 port=27017 dbpath=./db 64-bit host=Sarans-MBP-189
2020-02-20T00:38:03.671-0600 I  CONTROL  [initandlisten] db version v4.2.3
2020-02-20T00:38:03.671-0600 I  CONTROL  [initandlisten] git version: 6874650b362138df74be53d366bbefc321ea32d4
2020-02-20T00:38:03.671-0600 I  CONTROL  [initandlisten] allocator: system
2020-02-20T00:38:03.671-0600 I  CONTROL  [initandlisten] modules: none
2020-02-20T00:38:03.671-0600 I  CONTROL  [initandlisten] build environment:
2020-02-20T00:38:03.671-0600 I  CONTROL  [initandlisten]     distarch: x86_64
2020-02-20T00:38:03.671-0600 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-02-20T00:38:03.671-0600 I  CONTROL  [initandlisten] options: { config: "mongoServer.config", net: { bindIp: "127.0.0.1", port: 27017 }, storage: { dbPath: "./db" }, systemLog: { destination: "file", logAppend: true, path: "./mongo.server.log" } }
2020-02-20T00:38:03.672-0600 E  STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
2020-02-20T00:38:03.672-0600 I  CONTROL  [initandlisten] now exiting
2020-02-20T00:38:03.672-0600 I  CONTROL  [initandlisten] shutting down with code:48
2020-02-26T13:58:51.168-0600 I  CONTROL  [main] ***** SERVER RESTARTED *****
2020-02-26T13:58:51.178-0600 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-02-26T13:58:51.184-0600 I  CONTROL  [initandlisten] MongoDB starting : pid=78721 port=27017 dbpath=./db 64-bit host=Nikhils-MBP-564.fios-router.home
2020-02-26T13:58:51.184-0600 I  CONTROL  [initandlisten] db version v4.2.3
2020-02-26T13:58:51.184-0600 I  CONTROL  [initandlisten] git version: 6874650b362138df74be53d366bbefc321ea32d4
2020-02-26T13:58:51.184-0600 I  CONTROL  [initandlisten] allocator: system
2020-02-26T13:58:51.184-0600 I  CONTROL  [initandlisten] modules: none
2020-02-26T13:58:51.184-0600 I  CONTROL  [initandlisten] build environment:
2020-02-26T13:58:51.184-0600 I  CONTROL  [initandlisten]     distarch: x86_64
2020-02-26T13:58:51.184-0600 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-02-26T13:58:51.184-0600 I  CONTROL  [initandlisten] options: { config: "mongoServer.config", net: { bindIp: "localhost", port: 27017 }, storage: { dbPath: "./db" }, systemLog: { destination: "file", logAppend: true, path: "./mongo.server.log" } }
2020-02-26T13:58:51.186-0600 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7680M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
2020-02-26T13:58:51.697-0600 I  STORAGE  [initandlisten] WiredTiger message [1582747131:697911][78721:0x1160795c0], txn-recover: Set global recovery timestamp: (0, 0)
2020-02-26T13:58:51.726-0600 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2020-02-26T13:58:51.752-0600 I  STORAGE  [initandlisten] Timestamp monitor starting
2020-02-26T13:58:51.754-0600 I  CONTROL  [initandlisten] 
2020-02-26T13:58:51.754-0600 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2020-02-26T13:58:51.754-0600 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2020-02-26T13:58:51.754-0600 I  CONTROL  [initandlisten] 
2020-02-26T13:58:51.757-0600 I  STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: c0f46cf0-744c-4102-a92a-1774c4175c0a and options: { uuid: UUID("c0f46cf0-744c-4102-a92a-1774c4175c0a") }
2020-02-26T13:58:51.782-0600 I  INDEX    [initandlisten] index build: done building index _id_ on ns admin.system.version
2020-02-26T13:58:51.783-0600 I  SHARDING [initandlisten] Marking collection admin.system.version as collection version: <unsharded>
2020-02-26T13:58:51.783-0600 I  COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.2
2020-02-26T13:58:51.783-0600 I  SHARDING [initandlisten] Marking collection local.system.replset as collection version: <unsharded>
2020-02-26T13:58:51.784-0600 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
2020-02-26T13:58:51.784-0600 I  SHARDING [initandlisten] Marking collection admin.system.roles as collection version: <unsharded>
2020-02-26T13:58:51.785-0600 I  STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 85eeed35-c0bc-47f4-af13-4ac572246594 and options: { capped: true, size: 10485760 }
2020-02-26T13:58:51.811-0600 I  INDEX    [initandlisten] index build: done building index _id_ on ns local.startup_log
2020-02-26T13:58:51.812-0600 I  SHARDING [initandlisten] Marking collection local.startup_log as collection version: <unsharded>
2020-02-26T13:58:51.812-0600 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory './db/diagnostic.data'
2020-02-26T13:58:51.816-0600 I  SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
2020-02-26T13:58:51.816-0600 I  NETWORK  [listener] Listening on /tmp/mongodb-27017.sock
2020-02-26T13:58:51.816-0600 I  NETWORK  [listener] Listening on 127.0.0.1
2020-02-26T13:58:51.816-0600 I  NETWORK  [listener] waiting for connections on port 27017
2020-02-26T13:58:51.816-0600 I  CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
2020-02-26T13:58:51.817-0600 I  STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with provided UUID: 689ff76e-3554-453a-9177-2941eecba13d and options: { uuid: UUID("689ff76e-3554-453a-9177-2941eecba13d") }
2020-02-26T13:58:51.843-0600 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index _id_ on ns config.system.sessions
2020-02-26T13:58:51.845-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60796 #1 (1 connection now open)
2020-02-26T13:58:51.851-0600 I  NETWORK  [conn1] received client metadata from 127.0.0.1:60796 conn1: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T13:58:51.853-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60797 #2 (2 connections now open)
2020-02-26T13:58:51.857-0600 I  NETWORK  [conn2] received client metadata from 127.0.0.1:60797 conn2: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T13:58:51.867-0600 I  INDEX    [LogicalSessionCacheRefresh] index build: starting on config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 } using method: Hybrid
2020-02-26T13:58:51.867-0600 I  INDEX    [LogicalSessionCacheRefresh] build may temporarily use up to 200 megabytes of RAM
2020-02-26T13:58:51.868-0600 I  INDEX    [LogicalSessionCacheRefresh] index build: collection scan done. scanned 0 total records in 0 seconds
2020-02-26T13:58:51.868-0600 I  INDEX    [LogicalSessionCacheRefresh] index build: inserted 0 keys from external sorter into index in 0 seconds
2020-02-26T13:58:51.873-0600 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index lsidTTLIndex on ns config.system.sessions
2020-02-26T13:58:52.003-0600 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>
2020-02-26T13:58:52.361-0600 I  NETWORK  [conn2] end connection 127.0.0.1:60797 (1 connection now open)
2020-02-26T13:58:52.361-0600 I  NETWORK  [conn1] end connection 127.0.0.1:60796 (0 connections now open)
2020-02-26T13:59:26.567-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60801 #3 (1 connection now open)
2020-02-26T13:59:26.567-0600 I  NETWORK  [conn3] received client metadata from 127.0.0.1:60801 conn3: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T13:59:26.568-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60802 #4 (2 connections now open)
2020-02-26T13:59:26.568-0600 I  NETWORK  [conn4] received client metadata from 127.0.0.1:60802 conn4: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T13:59:26.596-0600 I  CONTROL  [main] ***** SERVER RESTARTED *****
2020-02-26T13:59:26.605-0600 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-02-26T13:59:26.612-0600 I  CONTROL  [initandlisten] MongoDB starting : pid=78742 port=27017 dbpath=./db 64-bit host=Nikhils-MBP-564.fios-router.home
2020-02-26T13:59:26.612-0600 I  CONTROL  [initandlisten] db version v4.2.3
2020-02-26T13:59:26.612-0600 I  CONTROL  [initandlisten] git version: 6874650b362138df74be53d366bbefc321ea32d4
2020-02-26T13:59:26.612-0600 I  CONTROL  [initandlisten] allocator: system
2020-02-26T13:59:26.612-0600 I  CONTROL  [initandlisten] modules: none
2020-02-26T13:59:26.612-0600 I  CONTROL  [initandlisten] build environment:
2020-02-26T13:59:26.612-0600 I  CONTROL  [initandlisten]     distarch: x86_64
2020-02-26T13:59:26.612-0600 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-02-26T13:59:26.612-0600 I  CONTROL  [initandlisten] options: { config: "mongoServer.config", net: { bindIp: "localhost", port: 27017 }, storage: { dbPath: "./db" }, systemLog: { destination: "file", logAppend: true, path: "./mongo.server.log" } }
2020-02-26T13:59:26.613-0600 E  STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
2020-02-26T13:59:26.613-0600 I  CONTROL  [initandlisten] now exiting
2020-02-26T13:59:26.613-0600 I  CONTROL  [initandlisten] shutting down with code:48
2020-02-26T13:59:27.080-0600 I  NETWORK  [conn3] end connection 127.0.0.1:60801 (1 connection now open)
2020-02-26T13:59:27.080-0600 I  NETWORK  [conn4] end connection 127.0.0.1:60802 (0 connections now open)
2020-02-26T14:00:34.458-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60809 #5 (1 connection now open)
2020-02-26T14:00:34.458-0600 I  NETWORK  [conn5] received client metadata from 127.0.0.1:60809 conn5: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:00:34.460-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60810 #6 (2 connections now open)
2020-02-26T14:00:34.460-0600 I  NETWORK  [conn6] received client metadata from 127.0.0.1:60810 conn6: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:00:34.489-0600 I  CONTROL  [main] ***** SERVER RESTARTED *****
2020-02-26T14:00:34.496-0600 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-02-26T14:00:34.503-0600 I  CONTROL  [initandlisten] MongoDB starting : pid=78761 port=27017 dbpath=./db 64-bit host=Nikhils-MBP-564.fios-router.home
2020-02-26T14:00:34.503-0600 I  CONTROL  [initandlisten] db version v4.2.3
2020-02-26T14:00:34.503-0600 I  CONTROL  [initandlisten] git version: 6874650b362138df74be53d366bbefc321ea32d4
2020-02-26T14:00:34.503-0600 I  CONTROL  [initandlisten] allocator: system
2020-02-26T14:00:34.503-0600 I  CONTROL  [initandlisten] modules: none
2020-02-26T14:00:34.503-0600 I  CONTROL  [initandlisten] build environment:
2020-02-26T14:00:34.503-0600 I  CONTROL  [initandlisten]     distarch: x86_64
2020-02-26T14:00:34.503-0600 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-02-26T14:00:34.503-0600 I  CONTROL  [initandlisten] options: { config: "mongoServer.config", net: { bindIp: "localhost", port: 27017 }, storage: { dbPath: "./db" }, systemLog: { destination: "file", logAppend: true, path: "./mongo.server.log" } }
2020-02-26T14:00:34.504-0600 E  STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
2020-02-26T14:00:34.505-0600 I  CONTROL  [initandlisten] now exiting
2020-02-26T14:00:34.505-0600 I  CONTROL  [initandlisten] shutting down with code:48
2020-02-26T14:00:34.975-0600 I  NETWORK  [conn5] end connection 127.0.0.1:60809 (0 connections now open)
2020-02-26T14:00:34.975-0600 I  NETWORK  [conn6] end connection 127.0.0.1:60810 (1 connection now open)
2020-02-26T14:03:51.819-0600 I  SHARDING [LogicalSessionCacheReap] Marking collection config.transactions as collection version: <unsharded>
2020-02-26T14:08:50.545-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60870 #7 (1 connection now open)
2020-02-26T14:08:50.545-0600 I  NETWORK  [conn7] received client metadata from 127.0.0.1:60870 conn7: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:08:50.546-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60871 #8 (2 connections now open)
2020-02-26T14:08:50.546-0600 I  NETWORK  [conn8] received client metadata from 127.0.0.1:60871 conn8: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:08:50.569-0600 I  CONTROL  [main] ***** SERVER RESTARTED *****
2020-02-26T14:08:50.579-0600 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-02-26T14:08:50.586-0600 I  CONTROL  [initandlisten] MongoDB starting : pid=78866 port=27017 dbpath=./db 64-bit host=Nikhils-MBP-564.fios-router.home
2020-02-26T14:08:50.586-0600 I  CONTROL  [initandlisten] db version v4.2.3
2020-02-26T14:08:50.586-0600 I  CONTROL  [initandlisten] git version: 6874650b362138df74be53d366bbefc321ea32d4
2020-02-26T14:08:50.586-0600 I  CONTROL  [initandlisten] allocator: system
2020-02-26T14:08:50.586-0600 I  CONTROL  [initandlisten] modules: none
2020-02-26T14:08:50.586-0600 I  CONTROL  [initandlisten] build environment:
2020-02-26T14:08:50.586-0600 I  CONTROL  [initandlisten]     distarch: x86_64
2020-02-26T14:08:50.586-0600 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-02-26T14:08:50.586-0600 I  CONTROL  [initandlisten] options: { config: "mongoServer.config", net: { bindIp: "localhost", port: 27017 }, storage: { dbPath: "./db" }, systemLog: { destination: "file", logAppend: true, path: "./mongo.server.log" } }
2020-02-26T14:08:50.588-0600 E  STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
2020-02-26T14:08:50.588-0600 I  CONTROL  [initandlisten] now exiting
2020-02-26T14:08:50.588-0600 I  CONTROL  [initandlisten] shutting down with code:48
2020-02-26T14:08:51.058-0600 I  NETWORK  [conn8] end connection 127.0.0.1:60871 (1 connection now open)
2020-02-26T14:08:51.058-0600 I  NETWORK  [conn7] end connection 127.0.0.1:60870 (0 connections now open)
2020-02-26T14:08:59.399-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60873 #9 (1 connection now open)
2020-02-26T14:08:59.399-0600 I  NETWORK  [conn9] received client metadata from 127.0.0.1:60873 conn9: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:08:59.400-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60874 #10 (2 connections now open)
2020-02-26T14:08:59.400-0600 I  NETWORK  [conn10] received client metadata from 127.0.0.1:60874 conn10: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:08:59.422-0600 I  CONTROL  [main] ***** SERVER RESTARTED *****
2020-02-26T14:08:59.425-0600 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-02-26T14:08:59.436-0600 I  CONTROL  [initandlisten] MongoDB starting : pid=78877 port=27017 dbpath=./db 64-bit host=Nikhils-MBP-564.fios-router.home
2020-02-26T14:08:59.436-0600 I  CONTROL  [initandlisten] db version v4.2.3
2020-02-26T14:08:59.436-0600 I  CONTROL  [initandlisten] git version: 6874650b362138df74be53d366bbefc321ea32d4
2020-02-26T14:08:59.436-0600 I  CONTROL  [initandlisten] allocator: system
2020-02-26T14:08:59.436-0600 I  CONTROL  [initandlisten] modules: none
2020-02-26T14:08:59.436-0600 I  CONTROL  [initandlisten] build environment:
2020-02-26T14:08:59.437-0600 I  CONTROL  [initandlisten]     distarch: x86_64
2020-02-26T14:08:59.437-0600 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-02-26T14:08:59.437-0600 I  CONTROL  [initandlisten] options: { config: "mongoServer.config", net: { bindIp: "localhost", port: 27017 }, storage: { dbPath: "./db" }, systemLog: { destination: "file", logAppend: true, path: "./mongo.server.log" } }
2020-02-26T14:08:59.438-0600 E  STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
2020-02-26T14:08:59.438-0600 I  CONTROL  [initandlisten] now exiting
2020-02-26T14:08:59.438-0600 I  CONTROL  [initandlisten] shutting down with code:48
2020-02-26T14:08:59.913-0600 I  NETWORK  [conn9] end connection 127.0.0.1:60873 (1 connection now open)
2020-02-26T14:08:59.913-0600 I  NETWORK  [conn10] end connection 127.0.0.1:60874 (0 connections now open)
2020-02-26T14:16:26.266-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60896 #11 (1 connection now open)
2020-02-26T14:16:26.266-0600 I  NETWORK  [conn11] received client metadata from 127.0.0.1:60896 conn11: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:16:26.268-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60897 #12 (2 connections now open)
2020-02-26T14:16:26.268-0600 I  NETWORK  [conn12] received client metadata from 127.0.0.1:60897 conn12: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:16:26.270-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-16 as collection version: <unsharded>
2020-02-26T14:16:26.272-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-17 as collection version: <unsharded>
2020-02-26T14:16:26.277-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-18 as collection version: <unsharded>
2020-02-26T14:16:26.278-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-19 as collection version: <unsharded>
2020-02-26T14:16:26.280-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-20 as collection version: <unsharded>
2020-02-26T14:16:26.282-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-21 as collection version: <unsharded>
2020-02-26T14:16:26.284-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-22 as collection version: <unsharded>
2020-02-26T14:16:26.285-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-23 as collection version: <unsharded>
2020-02-26T14:16:26.286-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-24 as collection version: <unsharded>
2020-02-26T14:16:26.286-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-25 as collection version: <unsharded>
2020-02-26T14:16:26.287-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-26 as collection version: <unsharded>
2020-02-26T14:16:26.287-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-27 as collection version: <unsharded>
2020-02-26T14:16:26.288-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-28 as collection version: <unsharded>
2020-02-26T14:16:26.288-0600 I  SHARDING [conn12] Marking collection timesheet.2020-02-29 as collection version: <unsharded>
2020-02-26T14:16:26.289-0600 I  SHARDING [conn12] Marking collection timesheet.2020-03-01 as collection version: <unsharded>
2020-02-26T14:16:26.289-0600 I  SHARDING [conn12] Marking collection timesheet.2020-03-02 as collection version: <unsharded>
2020-02-26T14:16:26.304-0600 I  CONTROL  [main] ***** SERVER RESTARTED *****
2020-02-26T14:16:26.305-0600 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-02-26T14:16:26.319-0600 I  CONTROL  [initandlisten] MongoDB starting : pid=78955 port=27017 dbpath=./db 64-bit host=Nikhils-MBP-564.fios-router.home
2020-02-26T14:16:26.319-0600 I  CONTROL  [initandlisten] db version v4.2.3
2020-02-26T14:16:26.319-0600 I  CONTROL  [initandlisten] git version: 6874650b362138df74be53d366bbefc321ea32d4
2020-02-26T14:16:26.319-0600 I  CONTROL  [initandlisten] allocator: system
2020-02-26T14:16:26.319-0600 I  CONTROL  [initandlisten] modules: none
2020-02-26T14:16:26.319-0600 I  CONTROL  [initandlisten] build environment:
2020-02-26T14:16:26.319-0600 I  CONTROL  [initandlisten]     distarch: x86_64
2020-02-26T14:16:26.319-0600 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-02-26T14:16:26.319-0600 I  CONTROL  [initandlisten] options: { config: "mongoServer.config", net: { bindIp: "localhost", port: 27017 }, storage: { dbPath: "./db" }, systemLog: { destination: "file", logAppend: true, path: "./mongo.server.log" } }
2020-02-26T14:16:26.320-0600 E  STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
2020-02-26T14:16:26.320-0600 I  CONTROL  [initandlisten] now exiting
2020-02-26T14:16:26.320-0600 I  CONTROL  [initandlisten] shutting down with code:48
2020-02-26T14:16:26.782-0600 I  NETWORK  [conn12] end connection 127.0.0.1:60897 (1 connection now open)
2020-02-26T14:16:26.782-0600 I  NETWORK  [conn11] end connection 127.0.0.1:60896 (0 connections now open)
2020-02-26T14:16:35.352-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60898 #13 (1 connection now open)
2020-02-26T14:16:35.353-0600 I  NETWORK  [conn13] received client metadata from 127.0.0.1:60898 conn13: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:16:35.354-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60899 #14 (2 connections now open)
2020-02-26T14:16:35.354-0600 I  NETWORK  [conn14] received client metadata from 127.0.0.1:60899 conn14: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:16:35.380-0600 I  CONTROL  [main] ***** SERVER RESTARTED *****
2020-02-26T14:16:35.387-0600 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-02-26T14:16:35.393-0600 I  CONTROL  [initandlisten] MongoDB starting : pid=78965 port=27017 dbpath=./db 64-bit host=Nikhils-MBP-564.fios-router.home
2020-02-26T14:16:35.393-0600 I  CONTROL  [initandlisten] db version v4.2.3
2020-02-26T14:16:35.393-0600 I  CONTROL  [initandlisten] git version: 6874650b362138df74be53d366bbefc321ea32d4
2020-02-26T14:16:35.393-0600 I  CONTROL  [initandlisten] allocator: system
2020-02-26T14:16:35.393-0600 I  CONTROL  [initandlisten] modules: none
2020-02-26T14:16:35.393-0600 I  CONTROL  [initandlisten] build environment:
2020-02-26T14:16:35.393-0600 I  CONTROL  [initandlisten]     distarch: x86_64
2020-02-26T14:16:35.393-0600 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-02-26T14:16:35.393-0600 I  CONTROL  [initandlisten] options: { config: "mongoServer.config", net: { bindIp: "localhost", port: 27017 }, storage: { dbPath: "./db" }, systemLog: { destination: "file", logAppend: true, path: "./mongo.server.log" } }
2020-02-26T14:16:35.394-0600 E  STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
2020-02-26T14:16:35.395-0600 I  CONTROL  [initandlisten] now exiting
2020-02-26T14:16:35.395-0600 I  CONTROL  [initandlisten] shutting down with code:48
2020-02-26T14:16:35.867-0600 I  NETWORK  [conn13] end connection 127.0.0.1:60898 (1 connection now open)
2020-02-26T14:16:35.867-0600 I  NETWORK  [conn14] end connection 127.0.0.1:60899 (0 connections now open)
2020-02-26T14:16:48.872-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60900 #15 (1 connection now open)
2020-02-26T14:16:48.872-0600 I  NETWORK  [conn15] received client metadata from 127.0.0.1:60900 conn15: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:16:48.873-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60901 #16 (2 connections now open)
2020-02-26T14:16:48.874-0600 I  NETWORK  [conn16] received client metadata from 127.0.0.1:60901 conn16: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:16:48.898-0600 I  CONTROL  [main] ***** SERVER RESTARTED *****
2020-02-26T14:16:48.901-0600 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-02-26T14:16:48.913-0600 I  CONTROL  [initandlisten] MongoDB starting : pid=78975 port=27017 dbpath=./db 64-bit host=Nikhils-MBP-564.fios-router.home
2020-02-26T14:16:48.913-0600 I  CONTROL  [initandlisten] db version v4.2.3
2020-02-26T14:16:48.913-0600 I  CONTROL  [initandlisten] git version: 6874650b362138df74be53d366bbefc321ea32d4
2020-02-26T14:16:48.913-0600 I  CONTROL  [initandlisten] allocator: system
2020-02-26T14:16:48.913-0600 I  CONTROL  [initandlisten] modules: none
2020-02-26T14:16:48.913-0600 I  CONTROL  [initandlisten] build environment:
2020-02-26T14:16:48.913-0600 I  CONTROL  [initandlisten]     distarch: x86_64
2020-02-26T14:16:48.913-0600 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-02-26T14:16:48.914-0600 I  CONTROL  [initandlisten] options: { config: "mongoServer.config", net: { bindIp: "localhost", port: 27017 }, storage: { dbPath: "./db" }, systemLog: { destination: "file", logAppend: true, path: "./mongo.server.log" } }
2020-02-26T14:16:48.915-0600 E  STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
2020-02-26T14:16:48.915-0600 I  CONTROL  [initandlisten] now exiting
2020-02-26T14:16:48.915-0600 I  CONTROL  [initandlisten] shutting down with code:48
2020-02-26T14:16:49.385-0600 I  NETWORK  [conn15] end connection 127.0.0.1:60900 (1 connection now open)
2020-02-26T14:16:49.385-0600 I  NETWORK  [conn16] end connection 127.0.0.1:60901 (0 connections now open)
2020-02-26T14:18:05.272-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60915 #17 (1 connection now open)
2020-02-26T14:18:05.273-0600 I  NETWORK  [conn17] received client metadata from 127.0.0.1:60915 conn17: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:18:05.274-0600 I  NETWORK  [listener] connection accepted from 127.0.0.1:60916 #18 (2 connections now open)
2020-02-26T14:18:05.274-0600 I  NETWORK  [conn18] received client metadata from 127.0.0.1:60916 conn18: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.14.6" }, platform: "CPython 3.7.3.final.0" }
2020-02-26T14:18:05.302-0600 I  CONTROL  [main] ***** SERVER RESTARTED *****
2020-02-26T14:18:05.303-0600 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-02-26T14:18:05.315-0600 I  CONTROL  [initandlisten] MongoDB starting : pid=79001 port=27017 dbpath=./db 64-bit host=Nikhils-MBP-564.fios-router.home
2020-02-26T14:18:05.315-0600 I  CONTROL  [initandlisten] db version v4.2.3
2020-02-26T14:18:05.315-0600 I  CONTROL  [initandlisten] git version: 6874650b362138df74be53d366bbefc321ea32d4
2020-02-26T14:18:05.315-0600 I  CONTROL  [initandlisten] allocator: system
2020-02-26T14:18:05.315-0600 I  CONTROL  [initandlisten] modules: none
2020-02-26T14:18:05.315-0600 I  CONTROL  [initandlisten] build environment:
2020-02-26T14:18:05.315-0600 I  CONTROL  [initandlisten]     distarch: x86_64
2020-02-26T14:18:05.315-0600 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-02-26T14:18:05.315-0600 I  CONTROL  [initandlisten] options: { config: "mongoServer.config", net: { bindIp: "localhost", port: 27017 }, storage: { dbPath: "./db" }, systemLog: { destination: "file", logAppend: true, path: "./mongo.server.log" } }
2020-02-26T14:18:05.317-0600 E  STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
2020-02-26T14:18:05.317-0600 I  CONTROL  [initandlisten] now exiting
2020-02-26T14:18:05.317-0600 I  CONTROL  [initandlisten] shutting down with code:48
2020-02-26T14:18:05.784-0600 I  NETWORK  [conn17] end connection 127.0.0.1:60915 (1 connection now open)
2020-02-26T14:18:05.784-0600 I  NETWORK  [conn18] end connection 127.0.0.1:60916 (0 connections now open)
